name: client_javascript:lint_and_test

on:
  push:
    branches:
      - main
    paths:
      - "clients/javascript/**"
  pull_request:
    branches:
      - main
    paths:
      - "clients/javascript/**"

defaults:
  run:
    working-directory: clients/javascript

jobs:
  test:
    name: lint-and-test-javascript-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: yarn install
      - run: yarn lint
      - run: yarn test
        id: test
