name: javascript:lint_and_test

on:
  push:
    branches:
      - main
    paths:
      - "packages/javascript/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/javascript/**"

defaults:
  run:
    working-directory: packages/javascript

jobs:
  test:
    name: lint-and-test-javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: packages/javascript/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
        id: test
