name: server:lint_and_test

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
  pull_request:
    branches:
      - main
    paths:
      - "server/**"

defaults:
  run:
    working-directory: server

jobs:
  test:
    name: lint-and-test-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: server/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
        id: test
